import assert from 'node:assert/strict';
import * as g from '../game.ts';
import { readFileSync } from 'node:fs';
const fixture = name => JSON.parse(readFileSync(new URL(`./fixtures/${name}.json`, import.meta.url), 'utf8'));
const T=1700000000000;
let count=0;
function test(name,fn){try{fn();console.log(`통과 ${++count}. ${name}`);}catch(e){console.error(`실패: ${name}`);throw e;}}
function tick(s,sec){const n=g.advance(s,T+sec*1000);g.validateState(n);return n;}
function act(s,a,sec){const n=g.reduce(s,a,T+sec*1000);g.validateState(n);return n;}
function prepared(n=10,mode='live',duration=900){const c=g.practiceConfig();c.rounds.forEach(r=>{r.blue=n;r.white=n;});c.timing.rounds=[duration,duration];let s=act(g.createGame(mode,c),{type:'START'},0);s=act(s,{type:'FIRST',round:0,team:'blue'},1);return act(s,{type:'FIRST',round:1,team:'white'},2);}
function play(n=10,duration=900){return act(prepared(n,'live',duration),{type:'START_ROUND',round:0},300);}
function highlight(s,sec,id){const e=s.selection,team=e.teams[e.index];return act(s,{type:'HIGHLIGHT',card:id??s.rounds[e.round].teams[team].picks[e.stage-1].candidates[0],eventId:e.id,team},sec);}
function confirm(s,sec,id){s=highlight(s,sec,id);const e=s.selection,team=e.teams[e.index];const required=g.targetCount(e.highlighted,s.rounds[e.round],team);if(required)s=act(s,{type:'TARGET_DRAFT',eventId:e.id,team,names:Array.from({length:required},(_,i)=>`선수${i+1}`)},sec);return act(s,{type:'CONFIRM',eventId:e.id,team},sec);}
function firstPicks(n=10){let s=play(n);s=confirm(s,301);s=confirm(s,302);return tick(s,304);}
function firstEarly(){let s=firstPicks();s=act(s,{type:'JUDGE',blue:-5,white:0,kind:'out'},310);s=act(s,{type:'EARLY',teams:['blue']},311);s=confirm(s,312);return tick(s,314);}
function selectSpecific(s,sec,card){let team=s.selection.teams[s.selection.index];if(!s.rounds[s.selection.round].teams[team].picks[s.selection.stage-1].candidates.includes(card)){s=confirm(s,sec);team=s.selection.teams[s.selection.index];}s=confirm(s,sec+1,card);return{state:s,team};}

test('시작 전 필수 설정, 초기 선공 미지정',()=>{let s=g.createGame();s=act(s,{type:'START'},0);assert.equal(s.flow,'setup');s=prepared();assert(s.config.rounds.every(r=>r.firstThrow));});
test('게임 시작 후 선공 선택, 규칙 확인 체크 없음',()=>{const c=g.practiceConfig();let s=act(g.createGame('live',c),{type:'FIRST',round:0,team:'blue'},0);assert.equal(s.config.rounds[0].firstThrow,null);s=act(s,{type:'START'},0);assert.equal(s.flow,'prepare');s=act(s,{type:'FIRST',round:0,team:'white'},1);assert.equal(s.config.rounds[0].firstThrow,'white');});
test('선공 두 팀 설정 후 슬라이드 열림·페이지 복구',()=>{let s=prepared();assert(s.intro.open);s=act(s,{type:'INTRO',open:true,index:8},3);assert.equal(g.parseState(JSON.stringify(s)).intro.index,8);});
test('준비 시간이 지나도 라운드가 임의로 시작되지 않음',()=>{let s=tick(prepared(),4000);assert.equal(s.flow,'prepare');assert.equal(s.selection,null);assert.equal(g.phaseRemaining(s,T+4000000),0);});
test('준비 완료 즉시 시작, 실제 시작 기준 15분·슬라이드 닫힘',()=>{let s=act(prepared(),{type:'START_ROUND',round:0},40);assert.equal(s.flow,'round1');assert.equal(s.rounds[0].startAt,T+40000);assert.equal(s.rounds[0].endAt,T+940000);assert(!s.intro.open);});
test('선공 미설정·잘못된 라운드 순서 시작 차단',()=>{let s=act(g.createGame('live',g.practiceConfig()),{type:'START'},0);s=act(s,{type:'START_ROUND',round:0},1);assert.equal(s.flow,'prepare');s=act(s,{type:'START_ROUND',round:1},1);assert.equal(s.flow,'prepare');s=act(s,{type:'START_ROUND',round:-1},1);assert.equal(s.flow,'prepare');});
test('같은 시작 버튼 중복 클릭은 시계를 재설정하지 않음',()=>{let s=play();const start=s.rounds[0].startAt;s=act(s,{type:'START_ROUND',round:0},305);assert.equal(s.rounds[0].startAt,start);});
test('각 라운드 다른 선공·증강 우선순위',()=>{let s=play();assert.equal(s.selection.teams[0],'white');s=act(s,{type:'END_ROUND',round:0},305);s=act(s,{type:'START_ROUND',round:1},306);assert.equal(s.selection.teams[0],'blue');});
test('후보 정확히 2장·후순위 전체 풀에서 선점 카드 제외',()=>{let s=play();assert.equal(s.rounds[0].teams.white.picks[0].candidates.length,2);s=confirm(s,310);const chosen=s.rounds[0].teams.white.picks[0].card;const candidates=s.rounds[0].teams.blue.picks[0].candidates;assert.equal(candidates.length,2);assert(!candidates.includes(chosen));});
test('첫 팀 39초 사용 후에도 다음 팀은 새 40초',()=>{let s=play();s=confirm(s,339);assert.equal(s.selection.index,1);assert.equal(s.selection.turnStartedAt,T+339000);assert.equal(s.selection.deadline,T+379000);});
test('첫 팀 시간 초과는 첫 팀만 확정, 두 번째 팀 40초',()=>{let s=play();const left=s.rounds[0].teams.white.picks[0].candidates[0];s=highlight(s,301,s.rounds[0].teams.white.picks[0].candidates[1]);s=tick(s,340);assert.equal(s.rounds[0].teams.white.picks[0].card,left);assert.equal(s.rounds[0].teams.blue.picks[0].card,null);assert.equal(s.selection.deadline,T+380000);s=tick(s,380);assert(s.rounds[0].teams.blue.picks[0].card);assert.notEqual(s.rounds[0].teams.blue.picks[0].card,left);});
test('단독 조기 선택도 한 팀 최대 40초',()=>{let s=firstPicks();s=act(s,{type:'JUDGE',blue:-5,white:0,kind:'out'},310);s=act(s,{type:'EARLY',teams:['blue']},311);assert.equal(s.selection.deadline,T+351000);assert.deepEqual(s.selection.teams,['blue']);});
test('완료 후 최대 1.5초 복귀 및 라운드 경계 우선',()=>{let s=play();s=confirm(s,301);s=confirm(s,302);assert(s.celebration);s=tick(s,303.5);assert.equal(s.celebration,null);let short=play(10,30);short=tick(short,330);assert.equal(short.flow,'switch');assert.equal(short.selection,null);});
test('팀 전환 시 오래된 확정 요청 중복 적용 방지',()=>{let s=play();const id=s.selection.id;s=confirm(s,301);const before=s.revision;s=act(s,{type:'CONFIRM',eventId:id,team:'white'},302);assert.equal(s.revision,before);});
test('지정형 카드 이름 없으면 수동 확정 차단',()=>{let s=play();const card=s.rounds[0].teams.white.picks[0].candidates.find(x=>g.CARD[x].targeted);assert(card);s=highlight(s,301,card);assert(!g.canConfirm(s));s=act(s,{type:'CONFIRM',eventId:s.selection.id,team:'white'},302);assert.equal(s.selection.index,0);});
test('자폭병·첫 피격 보호 1명 입력 후 확정 및 저장',()=>{let s=play();const card=s.rounds[0].teams.white.picks[0].candidates.find(x=>g.CARD[x].targeted);s=confirm(s,301,card);assert.deepEqual(s.rounds[0].teams.white.picks[0].targets,['선수1']);assert.deepEqual(g.parseState(JSON.stringify(s)).rounds[0].teams.white.picks[0].targets,['선수1']);});
test('커플 저주는 상대 선수 2명, 한 명·중복 이름 차단',()=>{let s=tick(firstPicks(),660);let team=s.selection.teams[0];if(!s.rounds[0].teams[team].picks[1].candidates.includes('couple')){s=confirm(s,661);team=s.selection.teams[1];}s=highlight(s,662,'couple');const id=s.selection.id;assert.equal(g.targetCount('couple',s.rounds[0],team),2);s=act(s,{type:'TARGET_DRAFT',eventId:id,team,names:['민수']},663);assert(!g.canConfirm(s));s=act(s,{type:'TARGET_DRAFT',eventId:id,team,names:['민수','민수']},664);assert(!g.canConfirm(s));s=act(s,{type:'TARGET_DRAFT',eventId:id,team,names:['민수','지훈']},665);assert(g.canConfirm(s));s=act(s,{type:'CONFIRM',eventId:id,team},666);assert.deepEqual(s.rounds[0].teams[team].picks[1].targets,['민수','지훈']);});
test('카드를 바꾸면 이전 대상 이름은 새 카드로 넘어가지 않음',()=>{let s=play();s=highlight(s,301);s=act(s,{type:'TARGET_DRAFT',eventId:s.selection.id,team:'white',names:['민수']},302);const other=s.rounds[0].teams.white.picks[0].candidates.find(c=>c!==s.selection.highlighted);s=highlight(s,303,other);assert.deepEqual(s.selection.targetNames,[]);});
test('현재 카드 다시 클릭하면 입력 중 이름 유지',()=>{let s=play();s=highlight(s,301);s=act(s,{type:'TARGET_DRAFT',eventId:s.selection.id,team:'white',names:['지훈']},302);s=highlight(s,303,s.selection.highlighted);assert.deepEqual(s.selection.targetNames,['지훈']);});
test('이름 초안·후보·현재 팀 제한 시각 새로고침 보존',()=>{let s=play();s=highlight(s,301);s=act(s,{type:'TARGET_DRAFT',eventId:s.selection.id,team:'white',names:['서준']},302);const restored=g.parseState(JSON.stringify(s));assert.deepEqual(restored.selection,s.selection);assert.deepEqual(restored.rounds,s.rounds);});
test('시간 초과 자동 지정은 가짜 이름을 만들지 않음·추후 보완',()=>{let s=play();s=tick(s,380);const team=g.TEAMS.find(t=>g.CARD[s.rounds[0].teams[t].picks[0].card].targeted);const p=s.rounds[0].teams[team].picks[0];assert.deepEqual(p.targets,[]);s=act(s,{type:'TARGETS',round:0,team,stage:1,names:['수빈']},381);assert.deepEqual(s.rounds[0].teams[team].picks[0].targets,['수빈']);});
test('외야 봉인 대상 숫자·이름 고정, 이후 추가 아웃 제외',()=>{let s=firstPicks();s=act(s,{type:'JUDGE',blue:-3,white:-2,kind:'out'},310);s=tick(s,1020);const chosen=selectSpecific(s,1021,'seal');s=chosen.state;const team=chosen.team,p=s.rounds[0].teams[team].picks[2],n=p.affectedCount;assert.equal(p.targets.length,n);s=tick(s,1102);s=act(s,{type:'JUDGE',blue:-1,white:-1,kind:'out'},1103);assert.equal(s.rounds[0].teams[team].picks[2].affectedCount,n);assert.equal(s.rounds[0].teams[team].picks[2].targets.length,n);});
test('10명 중 5명 아웃은 자격만 활성, 강제 팝업 없음',()=>{let s=firstPicks();s=act(s,{type:'JUDGE',blue:-5,white:0,kind:'out'},310);assert.equal(g.earlyStage(s,'blue',T+310000),2);assert.equal(s.selection,null);});
test('9명 중 현재 4명 불가·5명 가능',()=>{let s=firstPicks(9);s=act(s,{type:'JUDGE',blue:-4,white:0,kind:'out'},310);assert.equal(g.earlyStage(s,'blue',T+310000),null);s=act(s,{type:'JUDGE',blue:-1,white:0,kind:'out'},311);assert.equal(g.earlyStage(s,'blue',T+311000),2);});
test('누적 아웃 대신 현재 아웃 사용',()=>{let s=firstPicks();s=act(s,{type:'JUDGE',blue:-5,white:0,kind:'out'},310);s=act(s,{type:'JUDGE',blue:1,white:0,kind:'revive'},311);assert.equal(s.rounds[0].teams.blue.outs,5);assert.equal(g.earlyStage(s,'blue',T+311000),null);});
test('첫 조기 사용 후 2명에서는 불가, 1명 남으면 같은 액션 재활성',()=>{let s=firstEarly();s=act(s,{type:'JUDGE',blue:-3,white:0,kind:'out'},320);assert.equal(g.earlyStage(s,'blue',T+320000),null);s=act(s,{type:'JUDGE',blue:-1,white:0,kind:'out'},321);assert.equal(g.earlyStage(s,'blue',T+321000),3);s=act(s,{type:'EARLY',teams:['blue']},322);s=confirm(s,323);assert.equal(s.rounds[0].teams.blue.earlyUses,2);});
test('추가 조기 예약 복구·중복 클릭·시간 초과는 1회만 소비',()=>{let s=firstEarly();s=act(s,{type:'JUDGE',blue:-4,white:0,kind:'out'},320);s=act(s,{type:'EARLY',teams:['blue']},321);s=g.parseState(JSON.stringify(s));const id=s.selection.id;s=act(s,{type:'EARLY',teams:['blue']},322);assert.equal(s.selection.id,id);s=tick(s,361);assert.equal(s.rounds[0].teams.blue.earlyUses,2);});
test('추가 기회 쓰기 전 부활하면 비활성, 다시 1명이면 활성',()=>{let s=firstEarly();s=act(s,{type:'JUDGE',blue:-4,white:0,kind:'out'},320);s=act(s,{type:'JUDGE',blue:1,white:0,kind:'revive'},321);assert.equal(g.earlyStage(s,'blue',T+321000),null);s=act(s,{type:'JUDGE',blue:-1,white:0,kind:'out'},322);assert.equal(g.earlyStage(s,'blue',T+322000),3);});
test('두 조기 사용 후 정규 시각 건너뜀·팀당 3장 초과 없음',()=>{let s=firstEarly();s=act(s,{type:'JUDGE',blue:-4,white:0,kind:'out'},320);s=act(s,{type:'EARLY',teams:['blue']},321);s=confirm(s,322);s=tick(s,660);assert.deepEqual(s.selection.teams,['white']);s=tick(s,1020);assert.deepEqual(s.selection.teams,['white']);assert.equal(s.rounds[0].teams.blue.picks.filter(p=>p.card).length,3);});
test('양 팀 조기 선택 순서·각 팀 독립 40초',()=>{let s=firstPicks();s=act(s,{type:'JUDGE',blue:-5,white:-5,kind:'out'},310);s=act(s,{type:'EARLY',teams:g.TEAMS},311);assert.deepEqual(s.selection.teams,['white','blue']);s=confirm(s,330);assert.equal(s.selection.deadline,T+370000);});
test('조기 선택 도중 정규 단계 도래: 창 하나·대기열 처리',()=>{let s=firstPicks();s=act(s,{type:'JUDGE',blue:-5,white:0,kind:'out'},640);s=act(s,{type:'EARLY',teams:['blue']},650);const id=s.selection.id;s=tick(s,660);assert.equal(s.selection.id,id);assert.equal(s.queue.length,1);assert.deepEqual(s.queue[0].teams,['white']);s=tick(s,690);assert.deepEqual(s.selection.teams,['white']);assert.equal(s.selection.deadline,T+730000);});
test('정규 시각과 조기 버튼 충돌 시 정규 선택만 실행',()=>{let s=firstPicks();s=act(s,{type:'JUDGE',blue:-5,white:0,kind:'out'},640);s=act(s,{type:'EARLY',teams:['blue']},660);assert.equal(s.selection.kind,'regular');assert.equal(s.queue.length,0);});
test('추가 시간으로 라운드 종료 시각 연장·행사 40분 한도 없음',()=>{let s=firstPicks();s=act(s,{type:'ADD_TIME',seconds:3600,phaseId:g.phaseId(s)},350);assert.equal(s.rounds[0].endAt,T+4800000);s=tick(s,3000);assert.equal(s.flow,'round1');assert.equal(s.endAt,null);});
test('추가 시간은 증강 정규 6분·12분 시각을 뒤로 밀지 않음',()=>{let s=firstPicks();s=act(s,{type:'ADD_TIME',seconds:180,phaseId:g.phaseId(s)},400);s=tick(s,660);assert.equal(s.selection.stage,2);s=tick(s,1020);assert.equal(s.selection.stage,3);assert.equal(s.rounds[0].endAt,T+1380000);});
test('준비 0초 뒤 추가 시간은 요청한 만큼 온전히 부여',()=>{let s=tick(prepared(),400);s=act(s,{type:'ADD_TIME',seconds:60,phaseId:g.phaseId(s)},400);assert.equal(g.phaseRemaining(s,T+400000),60);});
test('라운드 종료 경계의 늦은 추가시간 요청이 다음 준비에 적용되지 않음',()=>{let s=firstPicks();const id=g.phaseId(s);s=act(s,{type:'ADD_TIME',seconds:300,phaseId:id},1200);assert.equal(s.flow,'switch');assert.equal(s.phaseEndAt,T+1320000);});
test('짧은 라운드에 추가시간 부여하면 현재 팀 선택도 최대 40초까지 확보',()=>{let s=play(10,30);assert.equal(s.selection.deadline,T+330000);s=act(s,{type:'ADD_TIME',seconds:60,phaseId:g.phaseId(s)},310);assert.equal(s.selection.deadline,T+340000);s=confirm(s,320);assert.equal(s.selection.deadline,T+360000);});
test('수동 조기 종료는 즉시 다음 라운드 준비 및 현재 생존 결과',()=>{let s=firstPicks();s=act(s,{type:'JUDGE',blue:-2,white:0,kind:'out'},310);s=act(s,{type:'END_ROUND',round:0},311);assert.equal(s.flow,'switch');assert.equal(s.rounds[0].result.winner,'white');assert.equal(s.rounds[0].result.reason,'manual');assert.equal(s.phaseStartAt,T+311000);});
test('선택 도중 조기 종료는 미확정 선택 정리·효과 종료·창 해제',()=>{let s=play();s=act(s,{type:'END_ROUND',round:0},310);assert.equal(s.selection,null);assert.equal(s.queue.length,0);assert.equal(s.flow,'switch');for(const t of g.TEAMS){assert(s.rounds[0].teams[t].picks[0].card);assert.equal(s.rounds[0].teams[t].picks[0].effect,'ended');}});
test('라운드 종료 버튼 중복 클릭은 다음 단계에 영향 없음',()=>{let s=firstPicks();s=act(s,{type:'END_ROUND',round:0},310);const before=s.revision;s=act(s,{type:'END_ROUND',round:0},311);assert.equal(s.revision,before);});
test('교체 화면에서 기다려도 2라운드 임의 시작 없음',()=>{let s=firstPicks();s=act(s,{type:'END_ROUND',round:0},310);s=tick(s,5000);assert.equal(s.flow,'switch');assert(!s.rounds[1].started);});
test('2라운드는 진행자 클릭 시각으로 시작, 이전 결과 유지·권리 초기화',()=>{let s=firstEarly();s=act(s,{type:'END_ROUND',round:0},320);const result=structuredClone(s.rounds[0].result);s=act(s,{type:'START_ROUND',round:1},350);assert.deepEqual(s.rounds[0].result,result);assert.equal(s.rounds[1].startAt,T+350000);assert.equal(s.rounds[1].teams.blue.earlyUses,0);assert(s.rounds[1].teams.blue.picks.every(p=>!p.card));});
test('라운드 시간 만료도 즉시 준비 화면으로 전환',()=>{let s=tick(play(),1200);assert.equal(s.flow,'switch');assert.equal(s.rounds[0].result.reason,'time');});
test('전멸이 조기 자격보다 우선하며 즉시 다음 준비',()=>{let s=firstPicks();s=act(s,{type:'JUDGE',blue:-10,white:0,kind:'out'},310);assert.equal(s.flow,'switch');assert.equal(g.earlyStage(s,'blue',T+310000),null);assert.equal(s.rounds[0].result.winner,'white');});
test('양 팀 동시 전멸 무승부·준비 화면에서 직전 판정 취소 복구',()=>{let s=firstPicks();s=act(s,{type:'JUDGE',blue:-10,white:-10,kind:'out'},310);assert.equal(s.rounds[0].result.winner,'draw');assert.equal(g.undoRound(s,T+311000),0);s=act(s,{type:'UNDO'},311);assert.equal(s.flow,'round1');assert.equal(s.rounds[0].result,null);assert.equal(s.rounds[0].teams.blue.alive,10);assert.equal(s.rounds[0].endAt,T+1200000);});
test('전멸 취소가 지난 정규 단계 선택을 복원',()=>{let s=firstPicks();s=act(s,{type:'JUDGE',blue:-10,white:0,kind:'out'},650);s=tick(s,670);s=act(s,{type:'UNDO'},671);assert.equal(s.flow,'round1');assert.equal(s.selection.stage,2);assert.equal(s.selection.deadline,T+711000);});
test('시간 만료·수동 종료·다음 라운드 시작 뒤 이전 판정 취소로 재개 불가',()=>{let s=firstPicks();s=act(s,{type:'JUDGE',blue:-1,white:0,kind:'out'},310);s=act(s,{type:'END_ROUND',round:0},311);assert.equal(g.undoRound(s,T+312000),null);s=act(s,{type:'START_ROUND',round:1},313);assert.equal(s.undo.length,0);let t=firstPicks();t=act(t,{type:'JUDGE',blue:-1,white:0,kind:'out'},310);t=tick(t,1200);assert.equal(g.undoRound(t,T+1201000),null);});
test('인원 범위·판정 수정 통계 분리·클릭 취소',()=>{let s=firstPicks();const before=s.revision;s=act(s,{type:'JUDGE',blue:1,white:0,kind:'revive'},310);s=act(s,{type:'JUDGE',blue:-11,white:0,kind:'out'},311);assert.equal(s.revision,before);s=act(s,{type:'JUDGE',blue:-3,white:0,kind:'correction'},312);assert.equal(s.rounds[0].teams.blue.outs,0);s=act(s,{type:'UNDO'},313);assert.equal(s.rounds[0].teams.blue.alive,10);});
test('선택 정정은 원래 후보·상대 독점 유지, 이름은 재지정',()=>{let s=firstPicks();for(const team of g.TEAMS){const p=s.rounds[0].teams[team].picks[0],candidate=p.candidates.find(id=>id!==p.card),before=structuredClone(p);s=act(s,{type:'CORRECT_PICK',team,stage:1,card:candidate},310);const next=s.rounds[0].teams[team].picks[0];if(candidate===s.rounds[0].teams[g.other(team)].picks[0].card)assert.equal(next.card,before.card);else{assert.equal(next.card,candidate);assert.deepEqual(next.targets,[]);}assert.deepEqual(next.candidates,before.candidates);assert.equal(next.chosenAt,before.chosenAt);}});
test('짐볼 독점과 다음 라운드 풀 초기화',()=>{let s=tick(firstPicks(),1020);const chosen=selectSpecific(s,1021,'gymball');s=chosen.state;const team=chosen.team;assert(!s.rounds[0].teams[g.other(team)].picks[2].candidates.includes('gymball')||s.rounds[0].teams[g.other(team)].picks[2].card!=='gymball');s=act(s,{type:'END_ROUND',round:0},1025);s=act(s,{type:'START_ROUND',round:1},1026);assert(s.rounds[1].teams.blue.picks.every(p=>!p.card));});
test('장시간 비활성 복구는 같은 이벤트를 반복하지 않음',()=>{let s=tick(play(),3000);assert.equal(s.flow,'switch');assert.equal(s.rounds[0].teams.blue.picks.filter(p=>p.card).length,3);assert.equal(s.processed.length,4);const rev=s.revision;s=tick(s,4000);assert.equal(s.revision,rev);});
test('마무리 화면은 진행자 종료 전까지 유지·추가 시간 가능',()=>{let s=act(firstPicks(),{type:'END_ROUND',round:0},310);s=act(s,{type:'START_ROUND',round:1},320);s=act(s,{type:'END_ROUND',round:1},321);s=tick(s,5000);assert.equal(s.flow,'finish');s=act(s,{type:'ADD_TIME',seconds:120,phaseId:g.phaseId(s)},5000);assert.equal(g.phaseRemaining(s,T+5000000),120);s=act(s,{type:'FINISH_EVENT'},5001);assert.equal(s.flow,'ended');assert.equal(g.elapsed(s,T+6000000),5001);});
test('승점→생존 합계→실제 가위바위보 및 종료 후 입력 차단',()=>{let s=firstPicks();s=act(s,{type:'JUDGE',blue:-2,white:0,kind:'out'},310);s=act(s,{type:'END_ROUND',round:0},311);s=act(s,{type:'START_ROUND',round:1},320);s=confirm(s,321);s=confirm(s,322);s=tick(s,324);s=act(s,{type:'JUDGE',blue:0,white:-3,kind:'out'},325);s=act(s,{type:'END_ROUND',round:1},326);assert.equal(g.scores(s).winner,'blue');let t=act(firstPicks(),{type:'END_ROUND',round:0},310);t=act(t,{type:'START_ROUND',round:1},320);t=act(t,{type:'END_ROUND',round:1},321);assert.equal(g.scores(t).winner,null);t=act(t,{type:'RPS',team:'white'},322);assert.equal(g.scores(t).winner,'white');t=act(t,{type:'FINISH_EVENT'},323);t=act(t,{type:'RPS',team:'blue'},324);assert.equal(g.scores(t).winner,'white');});
test('연습 일시정지·시간 이동은 실전 기록과 분리',()=>{const live=prepared();let s=prepared(10,'practice');s=act(s,{type:'PAUSE'},10);assert.equal(g.elapsed(s,T+100000),10);s=act(s,{type:'SKIP',seconds:80},20);assert.equal(g.elapsed(s,T+100000),90);s=act(s,{type:'PAUSE'},100);assert.equal(g.elapsed(s,T+101000),91);assert.equal(live.offset,0);let l=act(live,{type:'SKIP',seconds:100},10);assert.equal(l.offset,0);});
test('중지 안내가 실제 시계를 멈추지 않음',()=>{let s=act(firstPicks(),{type:'STOP'},310);s=tick(s,400);assert.equal(g.phaseRemaining(s,T+400000),800);assert(s.stopped);});
test('조정된 마감·팀별 시각·이름 JSON 복구 불변',()=>{let s=play();s=confirm(s,310);s=highlight(s,311);s=act(s,{type:'TARGET_DRAFT',eventId:s.selection.id,team:'blue',names:['지수']},312);s=act(s,{type:'ADD_TIME',seconds:180,phaseId:g.phaseId(s)},313);const restored=g.parseState(JSON.stringify(s));assert.deepEqual(restored,s);});
test('구버전 2 진행 기록을 유동적 운영으로 이전',()=>{const s=fixture('v2-active');const migrated=g.parseState(JSON.stringify(s));assert.equal(migrated.version,3);assert.equal(migrated.flow,'round1');assert.equal(migrated.selection.deadline,s.selection.deadline);assert.deepEqual(migrated.rounds[0].teams.white.picks[0].candidates,s.rounds[0].teams.white.picks[0].candidates);});
test('구버전 전멸 결과 장부 이전·기록 보존',()=>{const s=fixture('v2-eliminated');const migrated=g.parseState(JSON.stringify(s));assert.equal(migrated.flow,'switch');assert.equal(migrated.rounds[0].result.winner,'white');assert(migrated.processed.includes('r0-end'));});
test('잘못된 버전·시계·선택권·이름·인원 JSON 거부',()=>{const s=play();for(const fn of[x=>x.version=9,x=>x.phaseEndAt=T,x=>x.selection.deadline=T+500000,x=>x.rounds[0].teams.blue.alive=-1,x=>x.selection.targetNames=[7],x=>x.rounds[0].teams.blue.earlyUses=3]){const bad=structuredClone(s);fn(bad);assert.throws(()=>g.validateState(bad));}});
test('시간·선공·선택·판정·취소·복구 무작위 1,500회',()=>{let s=firstPicks(),seed=918231;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<1500;i++){const sec=305+i;s=tick(s,sec);if(s.selection){if(random()<.45)s=confirm(s,sec);}else{const n=Math.floor(random()*8),team=random()<.5?'blue':'white';if(n<3){const delta=n===0?1:-1;s=act(s,{type:'JUDGE',blue:team==='blue'?delta:0,white:team==='white'?delta:0,kind:delta>0?'revive':'out'},sec);}else if(n===3)s=act(s,{type:'UNDO'},sec);else if(n===4)s=act(s,{type:'EARLY',teams:[team]},sec);else if(n===5)s=act(s,{type:'ADD_TIME',seconds:60,phaseId:g.phaseId(s)},sec);else if(n===6&&s.flow==='switch')s=act(s,{type:'START_ROUND',round:1},sec);else s=g.parseState(JSON.stringify(s));}g.validateState(s);}});
console.log(`\n검증 ${count}개 통과`);
